export enum ErrorCode {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  ENTITY_NOT_FOUND = 'ENTITY_NOT_FOUND',
  INVALID_OPERATION = 'INVALID_OPERATION',
  INVALID_USER_INPUT = 'INVALID_USER_INPUT',
  INVALID_GQL_FILTER_OPERATION = 'INVALID_GQL_FILTER_OPERATION',
  INVALID_GQL_SORT_OPERATION = 'INVALID_GQL_SORT_OPERATION',
  INVALID_LIMIT_VALUE = 'INVALID_LIMIT_VALUE',
  INVALID_START_VALUE = 'INVALID_START_VALUE',
  INVALID_STATUS_CODE = 'INVALID_STATUS_CODE',
  DUPLICATE_KEY = 'DUPLICATE_KEY',
  REJECTED_UPDATE = 'REJECTED_UPDATE',
  INVALID_API_KEY = 'INVALID_API_KEY',
}
