import { CryptoAssetEnum } from 'src/performance-tracking/graphql/enums/crypto-asset.enum';

export const getCryptoSymbol = (asset: CryptoAssetEnum): string => {
  const ast = asset.toUpperCase().replace(' ', '_');
  return CryptoAssetSymbolEnum[ast];
};

enum CryptoAssetSymbolEnum {
  BITCOIN = 'BTC',
  LITECOIN = 'LTC',
  RIPPLE = 'XRP',
  DOGECOIN = 'DOGE',
  MONERO = 'XMR',
  STELLAR = 'XLM',
  TETHER = 'USDT',
  ETHEREUM = 'ETH',
  ETHEREUM_CLASSIC = 'ETC',
  MAKER = 'MKR',
  BASIC_ATTENTION_TOKEN = 'BAT',
  EOS = 'EOS',
  BITCOIN_CASH = 'BCH',
  BNB = 'BNB',
  TRON = 'TRX',
  DECENTRALAND = 'MANA',
  CHAINLINK = 'LINK',
  CARDANO = 'ADA',
  FILECOIN = 'FIL',
  THETA_NETWORK = 'THETA',
  HUOBI_TOKEN = 'HT',
  RAVENCOIN = 'RVN',
  TEZOS = 'XTZ',
  VECHAIN = 'VET',
  QUANT = 'QNT',
  USD_COIN = 'USDC',
  CRONOS = 'CRONOS',
  WRAPPED_BITCOIN = 'WBTC',
  COSMOS = 'ATOM',
  POLYGON = 'MATIC',
  OKB = 'OKB',
  UNUS_SED_LEO = 'LEO',
  ALGORAND = 'ALGO',
  CHILIZ = 'CHZ',
  THORCHAIN = 'RUNE',
  TERRA_CLASSIC = 'LUNA',
  FTX_TOKEN = 'FTT',
  HEDERA = 'HBAR',
  BINANCE_USD = 'BUSD',
  DAI = 'DAI',
  SOLANA = 'SOL',
  AVALANCHE = 'AVAX',
  SHIBA_INU = 'SHIB',
  THE_SANDBOX = 'SAND',
  POLKADOT = 'DOT',
  ELROND = 'EGLD',
  UNISWAP = 'UNI',
  AAVE = 'AAVE',
  NEAR_PROTOCOL = 'NEAR',
  FLOW = 'FLOW',
  INTERNET_COMPUTER = 'ICP',
  CASPER = 'CSPR',
  TONCOIN = 'TON',
  CHAIN = 'CHAI',
  APECOIN = 'APE',
  APTOS = 'APTOS',
}
